---
- name: Apply secret
  k8s:
    state: present
    definition: "{{ lookup('template', '00-secret.yml') }}"

- name: Apply hcloud-cloud-controller-manager v1.7.0
  shell: kubectl apply -f https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/v1.7.0/deploy/v1.7.0-networks.yaml
  register: output
- debug: msg={{ output.stdout_lines }}
