---
apiVersion: v1
kind: ConfigMap

metadata:
  name: fip-controller-config
  namespace: fip-controller
data:
  config.json: |
    {
      "hcloud_floating_ips": [ "{{ floating_ip }}" ],
      "node_address_type": "external"
    }
