---
apiVersion: v1
kind: ConfigMap

metadata:
  name: fip-controller-config
  namespace: fip-controller
data:
  config.json: |
    {
      "hcloudFloatingIPs": [ "{{ floating_ip }}" ],
      "nodeAddressType": "external"
    }
