---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer

metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ cert_manager_letsencrypt_email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-staging-issuer-account-key
    # Enable the HTTP01 challenge mechanism for this Issuer
    http01: {}
    solvers:
    # An empty selector will 'match' all Certificate resources that
    # reference this Issuer.
    - selector: {}
      http01:
        ingress:
          class: traefik

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer

metadata:
  name: letsencrypt-production
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ cert_manager_letsencrypt_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-production-issuer-account-key
    # Enable the HTTP01 challenge mechanism for this Issuer
    http01: {}
    solvers:
    # An empty selector will 'match' all Certificate resources that
    # reference this Issuer.
    - selector: {}
      http01:
        ingress:
          class: traefik
