---
- name: Update APT package index
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  apt:
    state: present
    pkg: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt:
    state: present
    pkg: 
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable and start Docker
  service:
    name: docker
    enabled: yes
    state: started

- name: Add deploy user to docker group
  user:
    name: "deploy"
    groups: "docker"
    append: true