---
- hosts: nodes
  remote_user: deploy
  become: yes
  become_method: sudo
  roles:
    - role: ansible-role-users
      tags: users
    - role: ansible-role-harden-linux
      tags: harden-linux
    - role: ansible-role-docker
      tags: docker
    - role: ansible-role-hcloud-floating-ip
      tags: hcloud-floating-ip
